### ISSUE TITLE
ClassConfusion throwing an AttributeError

### ISSUE THREAD

**Issue by oo92** [muellerzr/ClassLosses#2]
Hi.

I’m currently going through Lesson 2 using the ClassConfusion class in Google Colab in the following way:

`ClassConfusion(interp, classes, is_ordered=False, figsize=(8,8))`

When I ran the cell, I was asked to enter a value for ‘k’, or the top images you will see. I didn’t know what this was about so I entered 5. I was met with the following error message:

```
0%|          | 0/3 [00:00<?, ?it/s]  0%|          | 0/3 [00:00<?, ?it/s]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-6a81612b4be5> in <module>()
----> 1 ClassConfusion(interp, classes, is_ordered=False, figsize=(8,8))

4 frames
/content/ClassConfusion/classConfusion.py in _plot_imgs(self, tab, i, **kwargs)
     92                 img, lbl = self.interp.data.valid_ds[idx]
     93                 fn = self.interp.data.valid_ds.x.items[idx]
---> 94                 fn = re.search('([^/*]+)_\d+.*$', str(fn)).group(0)
     95                 img.show(ax=ax[row, col])
     96                 ax[row,col].set_title(fn)

AttributeError: 'NoneType' object has no attribute 'group'
```

I know that we can’t really use widgets in Colab but I was under the impression that ClassConfusion would remedy that problem. Its my 1st time ever using it and I am a newbie so this is most likely on me.

Thank you.

**Comment by muellerzr** [comment]
How are your images saved away on file?

**Comment by muellerzr** [comment]
Can you give me an example filename from your dataset? (quickest way is to tell me the result of `data.valid_ds.x.items[0]`)

**Comment by oo92** [comment]
> Can you give me an example filename from your dataset? (quickest way is to tell me the result of `data.valid_ds.x.items[0]`)

`PosixPath('data/bears/teddys/00000120.jpg')`

**Comment by mrcchef** [comment]
same problem with me.

**Comment by muellerzr** [comment]
Can you try using the new version in `fastai2`? I have not updated this version for quite some time and don't plan on updating it due to the new library version. See here:

https://github.com/muellerzr/ClassConfusion2

**Comment by thhung** [comment]
I fixed this problem by set classList to a pair of classes but the problem now is no image showed.

**Comment by m-ali-awan** [comment]
> Can you try using the new version in `fastai2`? I have not updated this version for quite some time and don't plan on updating it due to the new library version. See here:
> 
> https://github.com/muellerzr/ClassConfusion2

Hi Muellezr, this link is broken?

**Comment by muellerzr** [comment]
ClassConfusion is a part of my fastinference library:

htttps://github.com/muellerzr/fastinference

**Comment by m-ali-awan** [comment]
Thanks Muellerzr for such quick help.
And I am getting  this error:
AttributeError: 'ClassificationInterpretation' object has no attribute 'data'

And this error usually shows up, sometimes we donot have .classes attribute, so why is it so?

And, now in fastai latest version, with plot_top_losses we cannot get heatmaps.Is there any way to have them?

Thanks..

**Comment by muellerzr** [comment]
Which version of fastai are you using @m-ali-awan? (for your question relating to this library)

**Comment by m-ali-awan** [comment]
I am using colab, and installing it via --upgrade flag..

**Comment by m-ali-awan** [comment]
It is 2.3.0

**Comment by muellerzr** [comment]
This is designed for fastai v1, not v2. You need to use fastinference for the v2 version (as I noted above)

**Comment by m-ali-awan** [comment]
Sorry, but where to find that?

**Comment by m-ali-awan** [comment]
> ClassConfusion is a part of my fastinference library:
> 
> htttps://github.com/muellerzr/fastinference

Isn't this for v2?

**Comment by muellerzr** [comment]
muellerzr.github.io/fastinference (also the first thing that pops up when you google "fastinference")

And yes, fastai 2.0.0 + is fastai v2

**Comment by m-ali-awan** [comment]
Now, it is throwing this error:

For:   ClassConfusion(interp, classlist, is_ordered=False, figsize=(8,8))

AttributeError: 'ClassificationInterpretation' object has no attribute 'data'

**Comment by muellerzr** [comment]
Please include stack traces for everything you are doing. If you are trying to use this library with fastai version 2, I ***repeat*** it will not work for this. Open an issue on the fastinference repository if you have any errors with it, and include a full stack trace, exactly how you installed the library, exactly how you used the library, how you built your Learner, and so forth. The repo is https://github.com/muellerzr/fastinference

**Comment by m-ali-awan** [comment]
Ok, thanks alot..
And sorry to disturb you...

**Comment by m-ali-awan** [comment]
Hi Mueller, I also checked you repo of WalkWithFastai..
But I cannnot find any helping code that can guide me to use Class Confusion for vision..?
